name: minesweeper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.2
  vibration: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/images/closed.jpeg
    - assets/images/opened_0.jpeg
    - assets/images/opened_1.jpeg
    - assets/images/opened_2.jpeg
    - assets/images/opened_3.jpeg
    - assets/images/opened_4.jpeg
    - assets/images/opened_5.jpeg
    - assets/images/opened_6.jpeg
    - assets/images/opened_7.jpeg
    - assets/images/opened_8.jpeg
    - assets/images/flag.jpeg
    - assets/images/bomb_0.jpeg
    - assets/images/bomb_1.jpeg

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
          # style: italic
          # weight: 700
